version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # Remove exposed port from app service since Caddy will handle external connections
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - uploads:/app/uploads
      - sqlite-data:/app/prisma
    restart: unless-stopped
    networks:
      - app_network
      
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app_network
    depends_on:
      - app

volumes:
  uploads:
    # Persistent volume for uploaded files
  sqlite-data:
    # Persistent volume for SQLite database
  caddy_data:
    # Persistent volume for Caddy certificates
  caddy_config:
    # Persistent volume for Caddy configuration

networks:
  app_network:
    driver: bridge
