version: '3.8'

services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      # - DATABASE_URL=file:./prisma/dev.db
      - CHECKPOINT_DISABLE=1
      - DISABLE_PRISMA_TELEMETRY=true
    env_file:
      - .env
    volumes:
      # Mount the source code for hot reloading
      - ./:/app
      # Exclude node_modules from the mount to use the container's node_modules
      - /app/node_modules
      - /app/.next
      # Persistent volumes
      - uploads:/app/uploads
      - sqlite-data:/app/prisma
    restart: unless-stopped
    networks:
      - app_network
    # Use nodemon or Next.js dev server command in Dockerfile.dev

volumes:
  uploads:
    # Persistent volume for uploaded files
  sqlite-data:
    # Persistent volume for SQLite database

networks:
  app_network:
    driver: bridge
