services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    # Explicitly clear the entrypoint from the base image
    entrypoint: []
    # Use our custom dev entrypoint script
    command: ["/bin/bash", "/app/docker-dev-entrypoint.sh"]
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - uploads:/app/uploads
      - db_data:/data
    restart: unless-stopped
    networks:
      - app_network
    # For Next.js Hot Module Replacement (HMR)
    stdin_open: true
    tty: true

volumes:
  node_modules:
  uploads:
  db_data:

networks:
  app_network:
    driver: bridge
