version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # Remove exposed port from app service since Caddy will handle external connections
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - uploads:/app/uploads
      - db_data:/data
    restart: unless-stopped
    networks:
      - app_network
      
  # caddy:
  #   image: caddy:2-alpine
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./Caddyfile:/etc/caddy/Caddyfile:ro
  #     - caddy_data:/data
  #     - caddy_config:/config
  #   networks:
  #     - app_network
  #   depends_on:
  #     - app

volumes:
  uploads:
  db_data:
  caddy_data:
  caddy_config:

networks:
  app_network:
    driver: bridge
