version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - uploads:/app/uploads
      - sqlite-data:/app/prisma
    restart: unless-stopped

volumes:
  uploads:
    # Persistent volume for uploaded files
  sqlite-data:
    # Persistent volume for SQLite database
