version: '3.8'

services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - CHECKPOINT_DISABLE=1
      - DISABLE_PRISMA_TELEMETRY=true
    env_file:
      - .env
    volumes:
      # Mount the source code for hot reloading
      - ./:/app
      # Exclude node_modules from the mount to use the container's node_modules
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    networks:
      - app_network
    # Use nodemon or Next.js dev server command in Dockerfile.dev

networks:
  app_network:
    driver: bridge
